import mysql from 'mysql2/promise';
import dotenv from 'dotenv';

dotenv.config();

const pool = mysql.createPool({
  connectionLimit: 10,
  host: process.env.DATABASE_URL?.split('@')[1]?.split('/')[0] || 'localhost',
  user: process.env.DATABASE_URL?.split('://')[1]?.split(':')[0] || 'root',
  password: process.env.DATABASE_URL?.split(':')[2]?.split('@')[0] || '',
  database: process.env.DATABASE_URL?.split('/')[3] || 'a1_english_game',
});

const avatarData = [
  {
    name: 'Happy Star',
    description: 'A cheerful star that celebrates correct answers',
    personality: 'encouraging',
    imageUrl: '/avatars/happy-star.svg',
  },
  {
    name: 'Laughing Sun',
    description: 'A playful sun with a big smile',
    personality: 'playful',
    imageUrl: '/avatars/laughing-sun.svg',
  },
  {
    name: 'Wise Owl',
    description: 'A thoughtful owl that provides guidance',
    personality: 'wise',
    imageUrl: '/avatars/wise-owl.svg',
  },
  {
    name: 'Friendly Robot',
    description: 'A helpful robot assistant',
    personality: 'helpful',
    imageUrl: '/avatars/friendly-robot.svg',
  },
  {
    name: 'Giggling Cloud',
    description: 'A fluffy cloud that laughs at jokes',
    personality: 'playful',
    imageUrl: '/avatars/giggling-cloud.svg',
  },
  {
    name: 'Trophy Champion',
    description: 'A trophy character celebrating victories',
    personality: 'encouraging',
    imageUrl: '/avatars/trophy-champion.svg',
  },
  {
    name: 'Teasing Monkey',
    description: 'A playful monkey with a sense of humor',
    personality: 'playful',
    imageUrl: '/avatars/teasing-monkey.svg',
  },
  {
    name: 'Magical Unicorn',
    description: 'A magical unicorn spreading joy',
    personality: 'encouraging',
    imageUrl: '/avatars/magical-unicorn.svg',
  },
  {
    name: 'Curious Penguin',
    description: 'An inquisitive penguin explorer',
    personality: 'helpful',
    imageUrl: '/avatars/curious-penguin.svg',
  },
  {
    name: 'Brilliant Rocket',
    description: 'A speedy rocket zooming through space',
    personality: 'encouraging',
    imageUrl: '/avatars/brilliant-rocket.svg',
  },
];

const questionsData = [
  // Pronouns - Subject
  {
    questionText: '_____ am a student.',
    questionArabic: 'أنا طالب. (املأ الفراغ بالضمير المناسب)',
    questionFrench: 'Je suis étudiant. (Complétez le blanc)',
    questionSpanish: 'Soy estudiante. (Completa el espacio)',
    questionGerman: 'Ich bin ein Schüler. (Füllen Sie die Lücke aus)',
    questionChinese: '我是学生。(填空)',
    correctAnswer: 'I',
    options: JSON.stringify(['I', 'You', 'He', 'She']),
    category: 'Pronouns - Subject',
    explanationEnglish: 'Use "I" for the first person singular subject.',
    explanationArabic: 'استخدم "I" للشخص الأول المفرد.',
    explanationFrench: 'Utilisez "I" pour la première personne du singulier.',
    explanationSpanish: 'Usa "I" para la primera persona del singular.',
    explanationGerman: 'Verwenden Sie "I" für die erste Person Singular.',
    explanationChinese: '对第一人称单数使用"I"。',
  },
  {
    questionText: '_____ is my friend.',
    questionArabic: 'هو صديقي. (املأ الفراغ بالضمير المناسب)',
    questionFrench: 'Il est mon ami. (Complétez le blanc)',
    questionSpanish: 'Él es mi amigo. (Completa el espacio)',
    questionGerman: 'Er ist mein Freund. (Füllen Sie die Lücke aus)',
    questionChinese: '他是我的朋友。(填空)',
    correctAnswer: 'He',
    options: JSON.stringify(['I', 'You', 'He', 'They']),
    category: 'Pronouns - Subject',
    explanationEnglish: 'Use "He" for a male person.',
    explanationArabic: 'استخدم "He" للشخص الذكر.',
    explanationFrench: 'Utilisez "He" pour une personne masculine.',
    explanationSpanish: 'Usa "He" para una persona masculina.',
    explanationGerman: 'Verwenden Sie "He" für eine männliche Person.',
    explanationChinese: '对男性使用"He"。',
  },
  {
    questionText: '_____ are happy.',
    questionArabic: 'هم سعداء. (املأ الفراغ بالضمير المناسب)',
    questionFrench: 'Ils sont heureux. (Complétez le blanc)',
    questionSpanish: 'Ellos son felices. (Completa el espacio)',
    questionGerman: 'Sie sind glücklich. (Füllen Sie die Lücke aus)',
    questionChinese: '他们很高兴。(填空)',
    correctAnswer: 'They',
    options: JSON.stringify(['He', 'She', 'It', 'They']),
    category: 'Pronouns - Subject',
    explanationEnglish: 'Use "They" for plural subjects.',
    explanationArabic: 'استخدم "They" للمواضيع الجمع.',
    explanationFrench: 'Utilisez "They" pour les sujets pluriels.',
    explanationSpanish: 'Usa "They" para sujetos plurales.',
    explanationGerman: 'Verwenden Sie "They" für Pluralsubjekte.',
    explanationChinese: '对复数主语使用"They"。',
  },
  // Pronouns - Object
  {
    questionText: 'She loves _____.',
    questionArabic: 'هي تحبني. (املأ الفراغ بضمير المفعول به)',
    questionFrench: 'Elle m\'aime. (Complétez le blanc)',
    questionSpanish: 'Ella me ama. (Completa el espacio)',
    questionGerman: 'Sie liebt mich. (Füllen Sie die Lücke aus)',
    questionChinese: '她爱我。(填空)',
    correctAnswer: 'me',
    options: JSON.stringify(['I', 'me', 'my', 'mine']),
    category: 'Pronouns - Object',
    explanationEnglish: 'Use "me" as the object pronoun.',
    explanationArabic: 'استخدم "me" كضمير المفعول به.',
    explanationFrench: 'Utilisez "me" comme pronom objet.',
    explanationSpanish: 'Usa "me" como pronombre de objeto.',
    explanationGerman: 'Verwenden Sie "me" als Objektpronomen.',
    explanationChinese: '使用"me"作为宾语代词。',
  },
  {
    questionText: 'I see _____.',
    questionArabic: 'أراه. (املأ الفراغ بضمير المفعول به)',
    questionFrench: 'Je le vois. (Complétez le blanc)',
    questionSpanish: 'Lo veo. (Completa el espacio)',
    questionGerman: 'Ich sehe ihn. (Füllen Sie die Lücke aus)',
    questionChinese: '我看到他。(填空)',
    correctAnswer: 'him',
    options: JSON.stringify(['he', 'him', 'his', 'her']),
    category: 'Pronouns - Object',
    explanationEnglish: 'Use "him" for male object pronoun.',
    explanationArabic: 'استخدم "him" لضمير المفعول به الذكر.',
    explanationFrench: 'Utilisez "him" pour le pronom objet masculin.',
    explanationSpanish: 'Usa "him" para el pronombre de objeto masculino.',
    explanationGerman: 'Verwenden Sie "him" für männliches Objektpronomen.',
    explanationChinese: '对男性宾语代词使用"him"。',
  },
  // Possessive Adjectives
  {
    questionText: 'This is _____ book.',
    questionArabic: 'هذا كتابي. (املأ الفراغ بصفة الملكية)',
    questionFrench: 'C\'est mon livre. (Complétez le blanc)',
    questionSpanish: 'Este es mi libro. (Completa el espacio)',
    questionGerman: 'Das ist mein Buch. (Füllen Sie die Lücke aus)',
    questionChinese: '这是我的书。(填空)',
    correctAnswer: 'my',
    options: JSON.stringify(['I', 'me', 'my', 'mine']),
    category: 'Possessive Adjectives',
    explanationEnglish: 'Use "my" before a noun to show possession.',
    explanationArabic: 'استخدم "my" قبل الاسم لإظهار الملكية.',
    explanationFrench: 'Utilisez "my" avant un nom pour montrer la possession.',
    explanationSpanish: 'Usa "my" antes de un sustantivo para mostrar posesión.',
    explanationGerman: 'Verwenden Sie "my" vor einem Substantiv, um Besitz zu zeigen.',
    explanationChinese: '在名词前使用"my"来表示所有权。',
  },
  {
    questionText: '_____ name is Sarah.',
    questionArabic: 'اسمها سارة. (املأ الفراغ بصفة الملكية)',
    questionFrench: 'Son nom est Sarah. (Complétez le blanc)',
    questionSpanish: 'Su nombre es Sarah. (Completa el espacio)',
    questionGerman: 'Ihr Name ist Sarah. (Füllen Sie die Lücke aus)',
    questionChinese: '她的名字是莎拉。(填空)',
    correctAnswer: 'Her',
    options: JSON.stringify(['She', 'Her', 'Hers', 'His']),
    category: 'Possessive Adjectives',
    explanationEnglish: 'Use "Her" before a noun for female possession.',
    explanationArabic: 'استخدم "Her" قبل الاسم لملكية الأنثى.',
    explanationFrench: 'Utilisez "Her" avant un nom pour la possession féminine.',
    explanationSpanish: 'Usa "Her" antes de un sustantivo para posesión femenina.',
    explanationGerman: 'Verwenden Sie "Her" vor einem Substantiv für weiblichen Besitz.',
    explanationChinese: '在名词前使用"Her"来表示女性所有权。',
  },
  // Possessive Pronouns
  {
    questionText: 'This book is _____.',
    questionArabic: 'هذا الكتاب لي. (املأ الفراغ بضمير الملكية)',
    questionFrench: 'Ce livre est le mien. (Complétez le blanc)',
    questionSpanish: 'Este libro es mío. (Completa el espacio)',
    questionGerman: 'Dieses Buch ist meins. (Füllen Sie die Lücke aus)',
    questionChinese: '这本书是我的。(填空)',
    correctAnswer: 'mine',
    options: JSON.stringify(['my', 'mine', 'me', 'I']),
    category: 'Possessive Pronouns',
    explanationEnglish: 'Use "mine" as a possessive pronoun (without a noun).',
    explanationArabic: 'استخدم "mine" كضمير ملكية (بدون اسم).',
    explanationFrench: 'Utilisez "mine" comme pronom possessif (sans nom).',
    explanationSpanish: 'Usa "mine" como pronombre posesivo (sin sustantivo).',
    explanationGerman: 'Verwenden Sie "mine" als Possessivpronomen (ohne Substantiv).',
    explanationChinese: '使用"mine"作为所有格代词(不带名词)。',
  },
  {
    questionText: 'The car is _____.',
    questionArabic: 'السيارة له. (املأ الفراغ بضمير الملكية)',
    questionFrench: 'La voiture est la sienne. (Complétez le blanc)',
    questionSpanish: 'El coche es suyo. (Completa el espacio)',
    questionGerman: 'Das Auto ist seins. (Füllen Sie die Lücke aus)',
    questionChinese: '这辆车是他的。(填空)',
    correctAnswer: 'his',
    options: JSON.stringify(['he', 'him', 'his', 'her']),
    category: 'Possessive Pronouns',
    explanationEnglish: 'Use "his" for male possessive pronoun.',
    explanationArabic: 'استخدم "his" لضمير الملكية الذكر.',
    explanationFrench: 'Utilisez "his" pour le pronom possessif masculin.',
    explanationSpanish: 'Usa "his" para el pronombre posesivo masculino.',
    explanationGerman: 'Verwenden Sie "his" für männliches Possessivpronomen.',
    explanationChinese: '对男性所有格代词使用"his"。',
  },
  // Question Words
  {
    questionText: '_____ is your name?',
    questionArabic: 'ما اسمك؟ (املأ الفراغ بأداة الاستفهام)',
    questionFrench: 'Quel est votre nom? (Complétez le blanc)',
    questionSpanish: '¿Cuál es tu nombre? (Completa el espacio)',
    questionGerman: 'Wie ist dein Name? (Füllen Sie die Lücke aus)',
    questionChinese: '你叫什么名字？(填空)',
    correctAnswer: 'What',
    options: JSON.stringify(['What', 'Where', 'When', 'Who']),
    category: 'Question Words',
    explanationEnglish: 'Use "What" to ask about things or information.',
    explanationArabic: 'استخدم "What" للسؤال عن الأشياء أو المعلومات.',
    explanationFrench: 'Utilisez "What" pour poser des questions sur les choses ou les informations.',
    explanationSpanish: 'Usa "What" para preguntar sobre cosas o información.',
    explanationGerman: 'Verwenden Sie "What", um nach Dingen oder Informationen zu fragen.',
    explanationChinese: '使用"What"询问事物或信息。',
  },
  {
    questionText: '_____ do you live?',
    questionArabic: 'أين تعيش؟ (املأ الفراغ بأداة الاستفهام)',
    questionFrench: 'Où habites-tu? (Complétez le blanc)',
    questionSpanish: '¿Dónde vives? (Completa el espacio)',
    questionGerman: 'Wo wohnst du? (Füllen Sie die Lücke aus)',
    questionChinese: '你住在哪里？(填空)',
    correctAnswer: 'Where',
    options: JSON.stringify(['What', 'Where', 'When', 'Why']),
    category: 'Question Words',
    explanationEnglish: 'Use "Where" to ask about places.',
    explanationArabic: 'استخدم "Where" للسؤال عن الأماكن.',
    explanationFrench: 'Utilisez "Where" pour poser des questions sur les lieux.',
    explanationSpanish: 'Usa "Where" para preguntar sobre lugares.',
    explanationGerman: 'Verwenden Sie "Where", um nach Orten zu fragen.',
    explanationChinese: '使用"Where"询问地点。',
  },
  {
    questionText: '_____ are you?',
    questionArabic: 'من أنت؟ (املأ الفراغ بأداة الاستفهام)',
    questionFrench: 'Qui es-tu? (Complétez le blanc)',
    questionSpanish: '¿Quién eres? (Completa el espacio)',
    questionGerman: 'Wer bist du? (Füllen Sie die Lücke aus)',
    questionChinese: '你是谁？(填空)',
    correctAnswer: 'Who',
    options: JSON.stringify(['What', 'Where', 'Who', 'How']),
    category: 'Question Words',
    explanationEnglish: 'Use "Who" to ask about people.',
    explanationArabic: 'استخدم "Who" للسؤال عن الناس.',
    explanationFrench: 'Utilisez "Who" pour poser des questions sur les personnes.',
    explanationSpanish: 'Usa "Who" para preguntar sobre personas.',
    explanationGerman: 'Verwenden Sie "Who", um nach Personen zu fragen.',
    explanationChinese: '使用"Who"询问人物。',
  },
  // Present Simple - Be
  {
    questionText: 'I _____ a teacher.',
    questionArabic: 'أنا معلم. (املأ الفراغ بالفعل المناسب)',
    questionFrench: 'Je suis un professeur. (Complétez le blanc)',
    questionSpanish: 'Soy un profesor. (Completa el espacio)',
    questionGerman: 'Ich bin ein Lehrer. (Füllen Sie die Lücke aus)',
    questionChinese: '我是老师。(填空)',
    correctAnswer: 'am',
    options: JSON.stringify(['am', 'is', 'are', 'be']),
    category: 'Present Simple - Be',
    explanationEnglish: 'Use "am" with "I".',
    explanationArabic: 'استخدم "am" مع "I".',
    explanationFrench: 'Utilisez "am" avec "I".',
    explanationSpanish: 'Usa "am" con "I".',
    explanationGerman: 'Verwenden Sie "am" mit "I".',
    explanationChinese: '与"I"一起使用"am"。',
  },
  {
    questionText: 'She _____ beautiful.',
    questionArabic: 'هي جميلة. (املأ الفراغ بالفعل المناسب)',
    questionFrench: 'Elle est belle. (Complétez le blanc)',
    questionSpanish: 'Ella es hermosa. (Completa el espacio)',
    questionGerman: 'Sie ist schön. (Füllen Sie die Lücke aus)',
    questionChinese: '她很漂亮。(填空)',
    correctAnswer: 'is',
    options: JSON.stringify(['am', 'is', 'are', 'be']),
    category: 'Present Simple - Be',
    explanationEnglish: 'Use "is" with he/she/it.',
    explanationArabic: 'استخدم "is" مع he/she/it.',
    explanationFrench: 'Utilisez "is" avec he/she/it.',
    explanationSpanish: 'Usa "is" con he/she/it.',
    explanationGerman: 'Verwenden Sie "is" mit he/she/it.',
    explanationChinese: '与he/she/it一起使用"is"。',
  },
  {
    questionText: 'We _____ students.',
    questionArabic: 'نحن طلاب. (املأ الفراغ بالفعل المناسب)',
    questionFrench: 'Nous sommes des étudiants. (Complétez le blanc)',
    questionSpanish: 'Somos estudiantes. (Completa el espacio)',
    questionGerman: 'Wir sind Schüler. (Füllen Sie die Lücke aus)',
    questionChinese: '我们是学生。(填空)',
    correctAnswer: 'are',
    options: JSON.stringify(['am', 'is', 'are', 'be']),
    category: 'Present Simple - Be',
    explanationEnglish: 'Use "are" with we/you/they.',
    explanationArabic: 'استخدم "are" مع we/you/they.',
    explanationFrench: 'Utilisez "are" avec we/you/they.',
    explanationSpanish: 'Usa "are" con we/you/they.',
    explanationGerman: 'Verwenden Sie "are" mit we/you/they.',
    explanationChinese: '与we/you/they一起使用"are"。',
  },
  // Present Simple - Verbs
  {
    questionText: 'He _____ to school every day.',
    questionArabic: 'هو يذهب إلى المدرسة كل يوم. (املأ الفراغ بالفعل المناسب)',
    questionFrench: 'Il va à l\'école tous les jours. (Complétez le blanc)',
    questionSpanish: 'Él va a la escuela todos los días. (Completa el espacio)',
    questionGerman: 'Er geht jeden Tag zur Schule. (Füllen Sie die Lücke aus)',
    questionChinese: '他每天去学校。(填空)',
    correctAnswer: 'goes',
    options: JSON.stringify(['go', 'goes', 'going', 'went']),
    category: 'Present Simple - Verbs',
    explanationEnglish: 'Add "s" to verbs with he/she/it in present simple.',
    explanationArabic: 'أضف "s" للأفعال مع he/she/it في الحاضر البسيط.',
    explanationFrench: 'Ajoutez "s" aux verbes avec he/she/it au présent simple.',
    explanationSpanish: 'Agrega "s" a los verbos con he/she/it en presente simple.',
    explanationGerman: 'Fügen Sie "s" zu Verben mit he/she/it im Simple Present hinzu.',
    explanationChinese: '在一般现在时中，对he/she/it的动词添加"s"。',
  },
  {
    questionText: 'They _____ English.',
    questionArabic: 'هم يتحدثون الإنجليزية. (املأ الفراغ بالفعل المناسب)',
    questionFrench: 'Ils parlent anglais. (Complétez le blanc)',
    questionSpanish: 'Hablan inglés. (Completa el espacio)',
    questionGerman: 'Sie sprechen Englisch. (Füllen Sie die Lücke aus)',
    questionChinese: '他们说英语。(填空)',
    correctAnswer: 'speak',
    options: JSON.stringify(['speak', 'speaks', 'speaking', 'spoke']),
    category: 'Present Simple - Verbs',
    explanationEnglish: 'Use base form with I/you/we/they.',
    explanationArabic: 'استخدم الصيغة الأساسية مع I/you/we/they.',
    explanationFrench: 'Utilisez la forme de base avec I/you/we/they.',
    explanationSpanish: 'Usa la forma base con I/you/we/they.',
    explanationGerman: 'Verwenden Sie die Grundform mit I/you/we/they.',
    explanationChinese: '对I/you/we/they使用基本形式。',
  },
  // Present Continuous
  {
    questionText: 'I _____ reading now.',
    questionArabic: 'أنا أقرأ الآن. (املأ الفراغ بالفعل المناسب)',
    questionFrench: 'Je lis maintenant. (Complétez le blanc)',
    questionSpanish: 'Estoy leyendo ahora. (Completa el espacio)',
    questionGerman: 'Ich lese gerade. (Füllen Sie die Lücke aus)',
    questionChinese: '我现在在读书。(填空)',
    correctAnswer: 'am',
    options: JSON.stringify(['am', 'is', 'are', 'be']),
    category: 'Present Continuous',
    explanationEnglish: 'Use "am" + verb-ing for present continuous with "I".',
    explanationArabic: 'استخدم "am" + verb-ing للحاضر المستمر مع "I".',
    explanationFrench: 'Utilisez "am" + verb-ing pour le présent continu avec "I".',
    explanationSpanish: 'Usa "am" + verb-ing para el presente continuo con "I".',
    explanationGerman: 'Verwenden Sie "am" + verb-ing für Present Continuous mit "I".',
    explanationChinese: '对"I"使用"am" + verb-ing表示现在进行时。',
  },
  {
    questionText: 'She _____ watching TV.',
    questionArabic: 'هي تشاهد التلفاز. (املأ الفراغ بالفعل المناسب)',
    questionFrench: 'Elle regarde la télévision. (Complétez le blanc)',
    questionSpanish: 'Ella está viendo televisión. (Completa el espacio)',
    questionGerman: 'Sie schaut fern. (Füllen Sie die Lücke aus)',
    questionChinese: '她在看电视。(填空)',
    correctAnswer: 'is',
    options: JSON.stringify(['am', 'is', 'are', 'be']),
    category: 'Present Continuous',
    explanationEnglish: 'Use "is" + verb-ing with he/she/it.',
    explanationArabic: 'استخدم "is" + verb-ing مع he/she/it.',
    explanationFrench: 'Utilisez "is" + verb-ing avec he/she/it.',
    explanationSpanish: 'Usa "is" + verb-ing con he/she/it.',
    explanationGerman: 'Verwenden Sie "is" + verb-ing mit he/she/it.',
    explanationChinese: '与he/she/it一起使用"is" + verb-ing。',
  },
  // Articles
  {
    questionText: 'I have _____ apple.',
    questionArabic: 'لدي تفاحة. (املأ الفراغ بأداة التعريف المناسبة)',
    questionFrench: 'J\'ai une pomme. (Complétez le blanc)',
    questionSpanish: 'Tengo una manzana. (Completa el espacio)',
    questionGerman: 'Ich habe einen Apfel. (Füllen Sie die Lücke aus)',
    questionChinese: '我有一个苹果。(填空)',
    correctAnswer: 'an',
    options: JSON.stringify(['a', 'an', 'the', 'no article']),
    category: 'Articles',
    explanationEnglish: 'Use "an" before vowel sounds.',
    explanationArabic: 'استخدم "an" قبل أصوات حروف العلة.',
    explanationFrench: 'Utilisez "an" avant les sons de voyelles.',
    explanationSpanish: 'Usa "an" antes de sonidos de vocales.',
    explanationGerman: 'Verwenden Sie "an" vor Vokallauten.',
    explanationChinese: '在元音前使用"an"。',
  },
  {
    questionText: 'She is _____ doctor.',
    questionArabic: 'هي طبيبة. (املأ الفراغ بأداة التعريف المناسبة)',
    questionFrench: 'Elle est une médecin. (Complétez le blanc)',
    questionSpanish: 'Ella es una doctora. (Completa el espacio)',
    questionGerman: 'Sie ist eine Ärztin. (Füllen Sie die Lücke aus)',
    questionChinese: '她是医生。(填空)',
    correctAnswer: 'a',
    options: JSON.stringify(['a', 'an', 'the', 'no article']),
    category: 'Articles',
    explanationEnglish: 'Use "a" before consonant sounds.',
    explanationArabic: 'استخدم "a" قبل أصوات الحروف الساكنة.',
    explanationFrench: 'Utilisez "a" avant les sons de consonnes.',
    explanationSpanish: 'Usa "a" antes de sonidos de consonantes.',
    explanationGerman: 'Verwenden Sie "a" vor Konsonantenlauten.',
    explanationChinese: '在辅音前使用"a"。',
  },
  {
    questionText: '_____ sun is bright.',
    questionArabic: 'الشمس مشرقة. (املأ الفراغ بأداة التعريف المناسبة)',
    questionFrench: 'Le soleil est brillant. (Complétez le blanc)',
    questionSpanish: 'El sol es brillante. (Completa el espacio)',
    questionGerman: 'Die Sonne ist hell. (Füllen Sie die Lücke aus)',
    questionChinese: '太阳很明亮。(填空)',
    correctAnswer: 'The',
    options: JSON.stringify(['A', 'An', 'The', 'no article']),
    category: 'Articles',
    explanationEnglish: 'Use "The" for unique things.',
    explanationArabic: 'استخدم "The" للأشياء الفريدة.',
    explanationFrench: 'Utilisez "The" pour les choses uniques.',
    explanationSpanish: 'Usa "The" para cosas únicas.',
    explanationGerman: 'Verwenden Sie "The" für einzigartige Dinge.',
    explanationChinese: '对独特的事物使用"The"。',
  },
  // Prepositions - Place
  {
    questionText: 'The book is _____ the table.',
    questionArabic: 'الكتاب على الطاولة. (املأ الفراغ بحرف الجر المناسب)',
    questionFrench: 'Le livre est sur la table. (Complétez le blanc)',
    questionSpanish: 'El libro está en la mesa. (Completa el espacio)',
    questionGerman: 'Das Buch ist auf dem Tisch. (Füllen Sie die Lücke aus)',
    questionChinese: '书在桌子上。(填空)',
    correctAnswer: 'on',
    options: JSON.stringify(['in', 'on', 'at', 'under']),
    category: 'Prepositions - Place',
    explanationEnglish: 'Use "on" for surfaces.',
    explanationArabic: 'استخدم "on" للأسطح.',
    explanationFrench: 'Utilisez "on" pour les surfaces.',
    explanationSpanish: 'Usa "on" para superficies.',
    explanationGerman: 'Verwenden Sie "on" für Oberflächen.',
    explanationChinese: '对表面使用"on"。',
  },
  {
    questionText: 'She is _____ the house.',
    questionArabic: 'هي في المنزل. (املأ الفراغ بحرف الجر المناسب)',
    questionFrench: 'Elle est dans la maison. (Complétez le blanc)',
    questionSpanish: 'Ella está en la casa. (Completa el espacio)',
    questionGerman: 'Sie ist im Haus. (Füllen Sie die Lücke aus)',
    questionChinese: '她在房子里。(填空)',
    correctAnswer: 'in',
    options: JSON.stringify(['in', 'on', 'at', 'under']),
    category: 'Prepositions - Place',
    explanationEnglish: 'Use "in" for enclosed spaces.',
    explanationArabic: 'استخدم "in" للمساحات المغلقة.',
    explanationFrench: 'Utilisez "in" pour les espaces clos.',
    explanationSpanish: 'Usa "in" para espacios cerrados.',
    explanationGerman: 'Verwenden Sie "in" für geschlossene Räume.',
    explanationChinese: '对封闭空间使用"in"。',
  },
  // Prepositions - Time
  {
    questionText: 'I wake up _____ 7 o\'clock.',
    questionArabic: 'أستيقظ في الساعة السابعة. (املأ الفراغ بحرف الجر المناسب)',
    questionFrench: 'Je me réveille à 7 heures. (Complétez le blanc)',
    questionSpanish: 'Me despierto a las 7 en punto. (Completa el espacio)',
    questionGerman: 'Ich wache um 7 Uhr auf. (Füllen Sie die Lücke aus)',
    questionChinese: '我在7点钟醒来。(填空)',
    correctAnswer: 'at',
    options: JSON.stringify(['in', 'on', 'at', 'for']),
    category: 'Prepositions - Time',
    explanationEnglish: 'Use "at" with specific times.',
    explanationArabic: 'استخدم "at" مع أوقات محددة.',
    explanationFrench: 'Utilisez "at" avec des heures précises.',
    explanationSpanish: 'Usa "at" con horas específicas.',
    explanationGerman: 'Verwenden Sie "at" mit bestimmten Zeiten.',
    explanationChinese: '对特定时间使用"at"。',
  },
  {
    questionText: 'My birthday is _____ May.',
    questionArabic: 'عيد ميلادي في مايو. (املأ الفراغ بحرف الجر المناسب)',
    questionFrench: 'Mon anniversaire est en mai. (Complétez le blanc)',
    questionSpanish: 'Mi cumpleaños es en mayo. (Completa el espacio)',
    questionGerman: 'Mein Geburtstag ist im Mai. (Füllen Sie die Lücke aus)',
    questionChinese: '我的生日在五月。(填空)',
    correctAnswer: 'in',
    options: JSON.stringify(['in', 'on', 'at', 'for']),
    category: 'Prepositions - Time',
    explanationEnglish: 'Use "in" with months.',
    explanationArabic: 'استخدم "in" مع الأشهر.',
    explanationFrench: 'Utilisez "in" avec les mois.',
    explanationSpanish: 'Usa "in" con meses.',
    explanationGerman: 'Verwenden Sie "in" mit Monaten.',
    explanationChinese: '对月份使用"in"。',
  },
  // Vocabulary - Family
  {
    questionText: 'My father\'s wife is my _____.',
    questionArabic: 'زوجة أبي هي _____. (املأ الفراغ بالكلمة المناسبة)',
    questionFrench: 'La femme de mon père est ma _____. (Complétez le blanc)',
    questionSpanish: 'La esposa de mi padre es mi _____. (Completa el espacio)',
    questionGerman: 'Die Frau meines Vaters ist meine _____. (Füllen Sie die Lücke aus)',
    questionChinese: '我父亲的妻子是我的_____。(填空)',
    correctAnswer: 'mother',
    options: JSON.stringify(['sister', 'mother', 'aunt', 'grandmother']),
    category: 'Vocabulary - Family',
    explanationEnglish: 'Your father\'s wife is your mother.',
    explanationArabic: 'زوجة أبيك هي أمك.',
    explanationFrench: 'La femme de votre père est votre mère.',
    explanationSpanish: 'La esposa de tu padre es tu madre.',
    explanationGerman: 'Die Frau deines Vaters ist deine Mutter.',
    explanationChinese: '你父亲的妻子是你的母亲。',
  },
  {
    questionText: 'My mother\'s son is my _____.',
    questionArabic: 'ابن أمي هو _____. (املأ الفراغ بالكلمة المناسبة)',
    questionFrench: 'Le fils de ma mère est mon _____. (Complétez le blanc)',
    questionSpanish: 'El hijo de mi madre es mi _____. (Completa el espacio)',
    questionGerman: 'Der Sohn meiner Mutter ist mein _____. (Füllen Sie die Lücke aus)',
    questionChinese: '我母亲的儿子是我的_____。(填空)',
    correctAnswer: 'brother',
    options: JSON.stringify(['father', 'brother', 'uncle', 'cousin']),
    category: 'Vocabulary - Family',
    explanationEnglish: 'Your mother\'s son is your brother.',
    explanationArabic: 'ابن أمك هو أخوك.',
    explanationFrench: 'Le fils de votre mère est votre frère.',
    explanationSpanish: 'El hijo de tu madre es tu hermano.',
    explanationGerman: 'Der Sohn deiner Mutter ist dein Bruder.',
    explanationChinese: '你母亲的儿子是你的兄弟。',
  },
  // Vocabulary - Colors
  {
    questionText: 'The sky is _____.',
    questionArabic: 'السماء زرقاء. (املأ الفراغ بالكلمة المناسبة)',
    questionFrench: 'Le ciel est _____. (Complétez le blanc)',
    questionSpanish: 'El cielo es _____. (Completa el espacio)',
    questionGerman: 'Der Himmel ist _____. (Füllen Sie die Lücke aus)',
    questionChinese: '天空是_____。(填空)',
    correctAnswer: 'blue',
    options: JSON.stringify(['red', 'blue', 'green', 'yellow']),
    category: 'Vocabulary - Colors',
    explanationEnglish: 'The sky is typically blue.',
    explanationArabic: 'السماء عادة ما تكون زرقاء.',
    explanationFrench: 'Le ciel est généralement bleu.',
    explanationSpanish: 'El cielo es típicamente azul.',
    explanationGerman: 'Der Himmel ist typischerweise blau.',
    explanationChinese: '天空通常是蓝色的。',
  },
  {
    questionText: 'Grass is _____.',
    questionArabic: 'العشب أخضر. (املأ الفراغ بالكلمة المناسبة)',
    questionFrench: 'L\'herbe est _____. (Complétez le blanc)',
    questionSpanish: 'El pasto es _____. (Completa el espacio)',
    questionGerman: 'Das Gras ist _____. (Füllen Sie die Lücke aus)',
    questionChinese: '草是_____。(填空)',
    correctAnswer: 'green',
    options: JSON.stringify(['red', 'blue', 'green', 'yellow']),
    category: 'Vocabulary - Colors',
    explanationEnglish: 'Grass is green.',
    explanationArabic: 'العشب أخضر.',
    explanationFrench: 'L\'herbe est verte.',
    explanationSpanish: 'El pasto es verde.',
    explanationGerman: 'Das Gras ist grün.',
    explanationChinese: '草是绿色的。',
  },
  // Vocabulary - Numbers
  {
    questionText: 'One plus one equals _____.',
    questionArabic: 'واحد زائد واحد يساوي _____. (املأ الفراغ بالكلمة المناسبة)',
    questionFrench: 'Un plus un égale _____. (Complétez le blanc)',
    questionSpanish: 'Uno más uno es igual a _____. (Completa el espacio)',
    questionGerman: 'Eins plus eins ist gleich _____. (Füllen Sie die Lücke aus)',
    questionChinese: '一加一等于_____。(填空)',
    correctAnswer: 'two',
    options: JSON.stringify(['one', 'two', 'three', 'four']),
    category: 'Vocabulary - Numbers',
    explanationEnglish: '1 + 1 = 2',
    explanationArabic: '1 + 1 = 2',
    explanationFrench: '1 + 1 = 2',
    explanationSpanish: '1 + 1 = 2',
    explanationGerman: '1 + 1 = 2',
    explanationChinese: '1 + 1 = 2',
  },
  // Vocabulary - Days
  {
    questionText: 'The first day of the week is _____.',
    questionArabic: 'أول يوم في الأسبوع هو _____. (املأ الفراغ بالكلمة المناسبة)',
    questionFrench: 'Le premier jour de la semaine est _____. (Complétez le blanc)',
    questionSpanish: 'El primer día de la semana es _____. (Completa el espacio)',
    questionGerman: 'Der erste Tag der Woche ist _____. (Füllen Sie die Lücke aus)',
    questionChinese: '一周的第一天是_____。(填空)',
    correctAnswer: 'Monday',
    options: JSON.stringify(['Sunday', 'Monday', 'Friday', 'Saturday']),
    category: 'Vocabulary - Days',
    explanationEnglish: 'Monday is the first day of the work week.',
    explanationArabic: 'الاثنين هو أول يوم في أسبوع العمل.',
    explanationFrench: 'Le lundi est le premier jour de la semaine de travail.',
    explanationSpanish: 'El lunes es el primer día de la semana laboral.',
    explanationGerman: 'Montag ist der erste Tag der Arbeitswoche.',
    explanationChinese: '星期一是工作周的第一天。',
  },
  // Greetings
  {
    questionText: '_____ morning!',
    questionArabic: 'صباح الخير! (املأ الفراغ بالكلمة المناسبة)',
    questionFrench: 'Bonjour! (Complétez le blanc)',
    questionSpanish: '¡Buenos días! (Completa el espacio)',
    questionGerman: 'Guten Morgen! (Füllen Sie die Lücke aus)',
    questionChinese: '早上好！(填空)',
    correctAnswer: 'Good',
    options: JSON.stringify(['Nice', 'Good', 'Hello', 'Hi']),
    category: 'Greetings',
    explanationEnglish: '"Good morning" is a common greeting.',
    explanationArabic: '"Good morning" هي تحية شائعة.',
    explanationFrench: '"Good morning" est une salutation courante.',
    explanationSpanish: '"Good morning" es un saludo común.',
    explanationGerman: '"Good morning" ist eine häufige Begrüßung.',
    explanationChinese: '"Good morning"是一个常见的问候。',
  },
  {
    questionText: 'Nice to _____ you.',
    questionArabic: 'يسعدني التعرف عليك. (املأ الفراغ بالكلمة المناسبة)',
    questionFrench: 'Enchanté de vous _____. (Complétez le blanc)',
    questionSpanish: 'Mucho gusto de _____. (Completa el espacio)',
    questionGerman: 'Schön, dich zu _____. (Füllen Sie die Lücke aus)',
    questionChinese: '很高兴_____你。(填空)',
    correctAnswer: 'meet',
    options: JSON.stringify(['see', 'meet', 'know', 'find']),
    category: 'Greetings',
    explanationEnglish: '"Nice to meet you" is a polite greeting.',
    explanationArabic: '"Nice to meet you" هي تحية مهذبة.',
    explanationFrench: '"Nice to meet you" est une salutation polie.',
    explanationSpanish: '"Nice to meet you" es un saludo educado.',
    explanationGerman: '"Nice to meet you" ist eine höfliche Begrüßung.',
    explanationChinese: '"Nice to meet you"是一个礼貌的问候。',
  },
];

const achievementsData = [
  {
    name: 'First Steps',
    description: 'Answer your first question correctly',
    icon: '🎯',
    requirement: 1,
    category: 'completion',
  },
  {
    name: 'Quick Learner',
    description: 'Answer 10 questions correctly',
    icon: '⚡',
    requirement: 10,
    category: 'score',
  },
  {
    name: 'Grammar Master',
    description: 'Answer 50 questions correctly',
    icon: '👑',
    requirement: 50,
    category: 'score',
  },
  {
    name: 'On Fire',
    description: 'Get a streak of 5 correct answers',
    icon: '🔥',
    requirement: 5,
    category: 'streak',
  },
  {
    name: 'Unstoppable',
    description: 'Get a streak of 10 correct answers',
    icon: '⭐',
    requirement: 10,
    category: 'streak',
  },
  {
    name: 'Perfect Day',
    description: 'Answer 20 questions in one session',
    icon: '✨',
    requirement: 20,
    category: 'completion',
  },
];

async function seedDatabase() {
  const connection = await pool.getConnection();

  try {
    console.log('🌱 Starting database seeding...');

    // Seed avatars
    console.log('📦 Seeding avatars...');
    for (const avatar of avatarData) {
      await connection.execute(
        'INSERT INTO avatars (name, description, imageUrl, personality) VALUES (?, ?, ?, ?)',
        [avatar.name, avatar.description, avatar.imageUrl, avatar.personality]
      );
    }
    console.log(`✅ Seeded ${avatarData.length} avatars`);

    // Seed questions
    console.log('📦 Seeding questions...');
    for (const question of questionsData) {
      await connection.execute(
        `INSERT INTO questions (
          questionText, questionArabic, questionFrench, questionSpanish, questionGerman, questionChinese,
          correctAnswer, options, category, difficulty,
          explanationEnglish, explanationArabic, explanationFrench, explanationSpanish, explanationGerman, explanationChinese,
          audioText
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          question.questionText,
          question.questionArabic,
          question.questionFrench,
          question.questionSpanish,
          question.questionGerman,
          question.questionChinese,
          question.correctAnswer,
          question.options,
          question.category,
          question.difficulty,
          question.explanationEnglish,
          question.explanationArabic,
          question.explanationFrench,
          question.explanationSpanish,
          question.explanationGerman,
          question.explanationChinese,
          question.audioText,
        ]
      );
    }
    console.log(`✅ Seeded ${questionsData.length} questions`);

    // Seed achievements
    console.log('📦 Seeding achievements...');
    for (const achievement of achievementsData) {
      await connection.execute(
        'INSERT INTO achievements (name, description, icon, requirement, category) VALUES (?, ?, ?, ?, ?)',
        [achievement.name, achievement.description, achievement.icon, achievement.requirement, achievement.category]
      );
    }
    console.log(`✅ Seeded ${achievementsData.length} achievements`);

    // Seed feedback messages for each avatar
    console.log('📦 Seeding feedback messages...');
    const correctFeedback = [
      {
        messageEnglish: 'Excellent! That\'s correct!',
        messageArabic: 'ممتاز! هذا صحيح!',
        messageFrench: 'Excellent! C\'est correct!',
        messageSpanish: '¡Excelente! ¡Eso es correcto!',
        messageGerman: 'Ausgezeichnet! Das ist richtig!',
        messageChinese: '太棒了！这是正确的！',
      },
      {
        messageEnglish: 'Great job! You got it!',
        messageArabic: 'عمل رائع! لقد حصلت عليه!',
        messageFrench: 'Excellent travail! Tu l\'as eu!',
        messageSpanish: '¡Buen trabajo! ¡Lo conseguiste!',
        messageGerman: 'Großartig! Du hast es geschafft!',
        messageChinese: '干得好！你做到了！',
      },
      {
        messageEnglish: 'Perfect! Well done!',
        messageArabic: 'مثالي! أحسنت!',
        messageFrench: 'Parfait! Bien joué!',
        messageSpanish: '¡Perfecto! ¡Bien hecho!',
        messageGerman: 'Perfekt! Gut gemacht!',
        messageChinese: '完美！干得好！',
      },
    ];

    const incorrectFeedback = [
      {
        messageEnglish: 'Not quite right, try again!',
        messageArabic: 'ليس صحيحاً تماماً، حاول مرة أخرى!',
        messageFrench: 'Pas tout à fait correct, réessaye!',
        messageSpanish: '¡No es del todo correcto, intenta de nuevo!',
        messageGerman: 'Nicht ganz richtig, versuchen Sie es erneut!',
        messageChinese: '不太对，再试一次！',
      },
      {
        messageEnglish: 'Oops! That\'s not right. Keep going!',
        messageArabic: 'آه! هذا ليس صحيحاً. استمر!',
        messageFrench: 'Oups! Ce n\'est pas correct. Continue!',
        messageSpanish: '¡Oops! Eso no es correcto. ¡Sigue!',
        messageGerman: 'Hoppla! Das ist nicht richtig. Weiter geht\'s!',
        messageChinese: '哎呀！那不对。继续！',
      },
      {
        messageEnglish: 'Not this time, but you\'ll get it!',
        messageArabic: 'ليس هذه المرة، لكنك ستحصل عليها!',
        messageFrench: 'Pas cette fois, mais tu vas l\'avoir!',
        messageSpanish: '¡No esta vez, pero lo conseguirás!',
        messageGerman: 'Diesmal nicht, aber du wirst es schaffen!',
        messageChinese: '这次不行，但你会成功的！',
      },
    ];

    let feedbackIndex = 0;
    for (let i = 1; i <= avatarData.length; i++) {
      // Add correct feedback
      const correctMsg = correctFeedback[feedbackIndex % correctFeedback.length];
      await connection.execute(
        `INSERT INTO feedbackMessages (
          avatarId, messageEnglish, messageArabic, messageFrench, messageSpanish, messageGerman, messageChinese, feedbackType
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          i,
          correctMsg.messageEnglish,
          correctMsg.messageArabic,
          correctMsg.messageFrench,
          correctMsg.messageSpanish,
          correctMsg.messageGerman,
          correctMsg.messageChinese,
          'correct',
        ]
      );

      // Add incorrect feedback
      const incorrectMsg = incorrectFeedback[feedbackIndex % incorrectFeedback.length];
      await connection.execute(
        `INSERT INTO feedbackMessages (
          avatarId, messageEnglish, messageArabic, messageFrench, messageSpanish, messageGerman, messageChinese, feedbackType
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          i,
          incorrectMsg.messageEnglish,
          incorrectMsg.messageArabic,
          incorrectMsg.messageFrench,
          incorrectMsg.messageSpanish,
          incorrectMsg.messageGerman,
          incorrectMsg.messageChinese,
          'incorrect',
        ]
      );

      feedbackIndex++;
    }
    console.log(`✅ Seeded feedback messages for ${avatarData.length} avatars`);

    console.log('✨ Database seeding completed successfully!');
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    throw error;
  } finally {
    connection.release();
    await pool.end();
  }
}

seedDatabase().catch(console.error);
